---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - name: Create vault user
      user:
        name: "{{ vault_user }}"
        state: present
    - name: Install unzip
      apt:
        name: unzip
        state: present
        update_cache: true
    - name: Download consul
      unarchive:
        src: "https://releases.hashicorp.com/consul/1.0.2/consul_1.0.2_linux_amd64.zip"
        dest: /usr/local/sbin
        creates: "/usr/local/sbin/consul"
        owner: root
        group: root
        mode: 0500
        remote_src: True
    - name: Check if Consul is running
      shell: ps aux | grep consul | grep -v grep
      ignore_errors: yes
      changed_when: false
      register: consul_running
    - name: Create consul config directory
      file:
        path: /etc/consul
        state: directory
    - name: Create consul ssl keys
      include_role:
        name: activated-openssl
      vars:
        cert_ca_cert_src: ./certs/ca.crt
        cert_ca_key_src: ./certs/ca.key
        cert_ca_conf_src: ./certs/cert.conf
        cert_ca_cert_name: localhost
        cert_extension_name: cert_ext
        cert_dest_directory: /etc/consul
        cert_name: consul
        cert_owner: root
        cert_group: root
    - name: Copy consul config
      copy:
        src: ./consul/config.json
        dest: /etc/consul/config.json
    - name: Start consul dev agent
      shell: nohup consul agent -config-dir=/etc/consul -retry-join=127.0.0.1 -bootstrap-expect=1 &
      when: consul_running.rc != 0
      tags:
        - skip_ansible_lint
  roles:
    - role: ansible-activated-vault
  vars:
    vault_storage: consul
    vault_tcp_listener_address: 0.0.0.0:8200
    vault_generate_key: True
    vault_ca_cert_src: ./certs/ca.crt
    vault_ca_key_src: ./certs/ca.key
    vault_ca_cert_name: localhost
    vault_ca_conf_src: ./certs/cert.conf
    vault_cert_extension_name: cert_ext
    vault_consul_client_generate_key: True
    vault_consul_client_ca_cert_src: ./certs/ca.crt
    vault_consul_client_ca_key_src: ./certs/ca.key
    vault_consul_client_ca_cert_name: localhost
    vault_consul_client_ca_conf_src: ./certs/cert.conf
    vault_consul_client_cert_extension_name: cert_ext

