---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - name: Install unzip
      apt:
        name: unzip
        state: present
        update_cache: true
    - name: Download vault
      unarchive:
        src: "https://releases.hashicorp.com/consul/1.0.2/consul_1.0.2_linux_amd64.zip"
        dest: /usr/local/sbin
        creates: "/usr/local/sbin/consul"
        owner: root
        group: root
        mode: 0500
        remote_src: True
    - name: Check if Consul is running
      shell: ps aux | grep consul | grep -v grep
      ignore_errors: yes
      changed_when: false
      register: consul_running
    - name: Create ca bundle
      file:
        path: /etc/ca
        state: directory
    - name: Create consul config directory
      file:
        path: /etc/consul
        state: directory
    - name: Create vault keys directory
      file:
        path: /etc/vault-keys
        state: directory
        owner: "{{ vault_user }}"
        group: "{{ vault_user }}"
    - name: Copy SSL CA
      copy:
        src: ./certs/ca.pem
        dest: "/etc/ca/ca.pem"
    - name: Copy consul keys
      copy:
        src: "./certs/{{ item }}"
        dest: /etc/consul
      with_items:
        - consul-server.crt
        - consul-server.key
    - name: Copy vault keys
      copy:
        src: "./certs/{{ item }}"
        dest: /etc/vault-keys
      with_items:
        - vault-consul-client.crt
        - vault-consul-client.key
        - vault-server.crt
        - vault-server.key
    - name: Copy consul config
      copy:
        src: ./consul/config.json
        dest: /etc/consul/config.json
    - name: Start consul dev agent
      shell: nohup consul agent -config-dir=/etc/consul -retry-join=127.0.0.1 -bootstrap-expect=1 &
      when: consul_running.rc != 0
  roles:
    - role: ansible-activated-vault
  vars:
    vault_storage: consul
    vault_tcp_listener_address: 0.0.0.0:8200
    vault_tls_ca_local_file: ./certs/ca.pem
    vault_tls_cert_local_file: ./certs/vault-server.crt
    vault_tls_key_local_file: ./certs/vault-server.key
    vault_consul_tls_ca_file: /etc/ca/ca.pem
    vault_consul_tls_cert_file: /etc/vault-keys/vault-consul-client.crt
    vault_consul_tls_key_file: /etc/vault-keys/vault-consul-client.key

